-- ============================================================
-- PUP-iFinder Database Schema
-- ============================================================

CREATE DATABASE IF NOT EXISTS pup_ifinder
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE pup_ifinder;

-- ============================================================
-- TABLE: section
-- Stores program sections (e.g., BSIT 1-A)
-- ============================================================
CREATE TABLE IF NOT EXISTS section (
  SectionID    INT AUTO_INCREMENT PRIMARY KEY,
  Program      VARCHAR(20)  NOT NULL,
  YearLevel    INT          NOT NULL,
  BlockNumber  VARCHAR(10)  NOT NULL,
  SectionCode  VARCHAR(30)  GENERATED ALWAYS AS (
                 CONCAT(Program, ' ', YearLevel, '-', BlockNumber)
               ) STORED,
  UNIQUE KEY uq_section (Program, YearLevel, BlockNumber)
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: student
-- ============================================================
CREATE TABLE IF NOT EXISTS student (
  StudentNumber VARCHAR(20)  PRIMARY KEY,
  StudentName   VARCHAR(100) NOT NULL,
  StudentType   VARCHAR(20)  NOT NULL,
  Email         VARCHAR(100) NOT NULL UNIQUE,
  Password      VARCHAR(255) NOT NULL,
  SectionID     INT          DEFAULT NULL,
  FOREIGN KEY (SectionID) REFERENCES section(SectionID)
    ON DELETE SET NULL
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: faculty
-- ============================================================
CREATE TABLE IF NOT EXISTS faculty (
  FacultyNumber VARCHAR(20)  PRIMARY KEY,
  FacultyName   VARCHAR(100) NOT NULL,
  FacultyEmail  VARCHAR(100) NOT NULL UNIQUE,
  Password      VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: subject
-- ============================================================
CREATE TABLE IF NOT EXISTS subject (
  SubjectCode  VARCHAR(30)  PRIMARY KEY,
  SubjectTitle VARCHAR(200) NOT NULL
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: subject_section
-- Links a subject to a section + assigns a faculty member
-- ============================================================
CREATE TABLE IF NOT EXISTS subject_section (
  SubjectSectionID INT          AUTO_INCREMENT PRIMARY KEY,
  SubjectCode      VARCHAR(30)  NOT NULL,
  SectionID        INT          NOT NULL,
  schedule         TEXT         DEFAULT NULL,
  FacultyNumber    VARCHAR(20)  DEFAULT NULL,
  FOREIGN KEY (SubjectCode)   REFERENCES subject(SubjectCode)  ON DELETE CASCADE,
  FOREIGN KEY (SectionID)     REFERENCES section(SectionID)   ON DELETE CASCADE,
  FOREIGN KEY (FacultyNumber) REFERENCES faculty(FacultyNumber) ON DELETE SET NULL,
  UNIQUE KEY uq_subject_section (SubjectCode, SectionID)
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: class_resource
-- Stores classroom links for each subject_section
-- ============================================================
CREATE TABLE IF NOT EXISTS class_resource (
  SubjectSectionID INT          PRIMARY KEY,
  Messenger        VARCHAR(500) DEFAULT NULL,
  GClassroom       VARCHAR(500) DEFAULT NULL,
  MSTeams          VARCHAR(500) DEFAULT NULL,
  Canvas           VARCHAR(500) DEFAULT NULL,
  GDrive           VARCHAR(500) DEFAULT NULL,
  additionallink1  VARCHAR(500) DEFAULT NULL,
  additionallink2  VARCHAR(500) DEFAULT NULL,
  FOREIGN KEY (SubjectSectionID) REFERENCES subject_section(SubjectSectionID)
    ON DELETE CASCADE
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: cor_subject
-- COR upload matching results per student
-- ============================================================
CREATE TABLE IF NOT EXISTS cor_subject (
  CorSubjectID           INT          AUTO_INCREMENT PRIMARY KEY,
  StudentNumber          VARCHAR(20)  NOT NULL,
  RawSubjectCode         VARCHAR(50)  NOT NULL,
  RawSectionCode         VARCHAR(50)  DEFAULT NULL,
  MatchedSectionID       INT          DEFAULT NULL,
  MatchedSubjectID       VARCHAR(30)  DEFAULT NULL,
  MatchedSubjectSectionID INT         DEFAULT NULL,
  MatchStatus            VARCHAR(20)  DEFAULT 'Unmatched',
  FOREIGN KEY (StudentNumber) REFERENCES student(StudentNumber) ON DELETE CASCADE,
  UNIQUE KEY uq_cor_subject (StudentNumber, RawSubjectCode)
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: authorization
-- Access codes generated by faculty for block reps
-- ============================================================
CREATE TABLE IF NOT EXISTS authorization (
  AuthID        INT         AUTO_INCREMENT PRIMARY KEY,
  FacultyNumber VARCHAR(20) NOT NULL,
  AccessCode    VARCHAR(20) NOT NULL UNIQUE,
  UsedBy        VARCHAR(20) DEFAULT NULL,
  FOREIGN KEY (FacultyNumber) REFERENCES faculty(FacultyNumber) ON DELETE CASCADE,
  FOREIGN KEY (UsedBy)        REFERENCES student(StudentNumber) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ============================================================
-- TABLE: blockrep
-- Stores which student is the block representative
-- ============================================================
CREATE TABLE IF NOT EXISTS blockrep (
  BlockRepID VARCHAR(20) PRIMARY KEY,
  SectionID  INT         NOT NULL,
  FOREIGN KEY (BlockRepID) REFERENCES student(StudentNumber) ON DELETE CASCADE,
  FOREIGN KEY (SectionID)  REFERENCES section(SectionID)    ON DELETE CASCADE,
  UNIQUE KEY uq_blockrep_section (SectionID)
) ENGINE=InnoDB;

-- ============================================================
-- STORED PROCEDURE: sp_update_subject_details
-- Used by faculty to update classroom links + faculty assignment
-- ============================================================
DELIMITER $$

CREATE PROCEDURE IF NOT EXISTS sp_update_subject_details(
  IN p_SubjectSectionID INT,
  IN p_FacultyNumber    VARCHAR(20),
  IN p_Messenger        VARCHAR(500),
  IN p_GClassroom       VARCHAR(500),
  IN p_MSTeams          VARCHAR(500),
  IN p_Canvas           VARCHAR(500),
  IN p_GDrive           VARCHAR(500),
  IN p_additionallink1  VARCHAR(500),
  IN p_additionallink2  VARCHAR(500)
)
BEGIN
  -- Update faculty assignment on the subject_section row
  UPDATE subject_section
  SET FacultyNumber = NULLIF(p_FacultyNumber, '')
  WHERE SubjectSectionID = p_SubjectSectionID;

  -- Upsert the class_resource row
  INSERT INTO class_resource
    (SubjectSectionID, Messenger, GClassroom, MSTeams, Canvas, GDrive, additionallink1, additionallink2)
  VALUES
    (p_SubjectSectionID, p_Messenger, p_GClassroom, p_MSTeams, p_Canvas, p_GDrive, p_additionallink1, p_additionallink2)
  ON DUPLICATE KEY UPDATE
    Messenger       = p_Messenger,
    GClassroom      = p_GClassroom,
    MSTeams         = p_MSTeams,
    Canvas          = p_Canvas,
    GDrive          = p_GDrive,
    additionallink1 = p_additionallink1,
    additionallink2 = p_additionallink2;
END$$

DELIMITER ;

-- ============================================================
-- SEED: Insert a test faculty account (optional)
-- Password: faculty123
-- ============================================================
INSERT IGNORE INTO faculty (FacultyNumber, FacultyName, FacultyEmail, Password)
VALUES ('FAC-001', 'Test Faculty', 'faculty@pup.edu.ph', 'faculty123');

SELECT 'Database setup complete!' AS Status;
